AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 30
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Documentation:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
  IndentationWidth: 2
